root: true
env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'next/core-web-vitals'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-cond-assign: ['error', 'except-parens']
  no-multiple-empty-lines: 'off'
  no-restricted-syntax: 'off'
  no-unused-vars: ['error', { 'vars': 'all', 'args': 'none' }]
  import/prefer-default-export: 'off'
  max-len: ['warn', 100]
  semi: ['error']
