root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-cond-assign: ['error', 'except-parens']
  no-multiple-empty-lines: 'off'
  no-restricted-syntax: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': ['error', { 'vars': 'all', 'args': 'none' }]
  '@typescript-eslint/no-non-null-assertion': ['warn']
  import/prefer-default-export: 'off'
  max-len: ['warn', 100]
  semi: 'off'
  '@typescript-eslint/semi': ['error']
