tabWidth: 2
trailingComma: es5
singleQuote: true
printWidth: 100
importOrder:
  - <THIRD_PARTY_MODULES>
  - ^[./]
importOrderCaseInsensitive: true
importOrderSeparation: true
importOrderSortSpecifiers: true
